### ISSUE TITLE
mixtral 8x7b and 8x22b please 

### ISSUE THREAD

**Issue by ehartford** [mistralai/mistral-finetune#11]
Would be really happy to see a reference implementation of finetuning 8x7b and 8x22b 

Thank you!  Love you guys!

**Comment by CyberTimon** [comment]
I'm interested too. +1

**Comment by patrickvonplaten** [comment]
Hey @ehartford,

You can fine-tune 8x7B and 8x22B exactly the same way you train the 7B. For the 8x7B you should probably use 2-4 80GB GPUs and for the 8x22B you will need 8x 80GB GPUs.

**Comment by ehartford** [comment]
> Hey @ehartford,
> 
> You can fine-tune 8x7B and 8x22B exactly the same way you train the 7B. For the 8x7B you should probably use 2-4 80GB GPUs and for the 8x22B you will need 8x 80GB GPUs.

I have my tricks 😜

**Comment by jagilley** [comment]
@ehartford it seems like there's built-in support for the way that Mistral implemented the MoE routing etc etc - is there some other implementation detail you were looking for?

**Comment by ehartford** [comment]
no; I'm happy with that!  I'll try it out.
