### ISSUE TITLE
`ValueError: min() arg is an empty sequence` in `utils.validate_data` script

### ISSUE THREAD

**Issue by aymenkrifa** [mistralai/mistral-finetune#17]
Walking through the fine-tuning notebook in Google Colab and just executing the cells without any changes, I get the following error when executing the following cell `!python -m utils.validate_data --train_yaml example/7B.yaml` :

> Traceback (most recent call last):
>   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
>     exec(code, run_globals)
>   File "/content/mistral-finetune/utils/validate_data.py", line 366, in <module>
>     main(args)
>   File "/content/mistral-finetune/utils/validate_data.py", line 173, in main
>     datasets, weights = parse_data_sources(pretrain_file, instruct_file)
>   File "/content/mistral-finetune/finetune/data/dataset.py", line 159, in parse_data_sources
>     assert min(n_weights) > 0
> ValueError: min() arg is an empty sequence

**Comment by patrickvonplaten** [comment]
Make to fix out `example/7B.yaml` with a valid path to a dataset
