### ISSUE TITLE
[BUG: ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (32768,) + inhomogeneous part.

### ISSUE THREAD

**Issue by nvnk3** [mistralai/mistral-finetune#99]
### Python Version

```shell
Python 3.9.18 (main, Jan 24 2024, 00:00:00) 
[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]
```

### Pip Freeze

```shell
absl-py==2.1.0
aiofiles==22.1.0
aiohttp==3.9.5
aiohttp-cors==0.7.0
aiosignal==1.3.1
aiosqlite==0.20.0
annotated-types==0.7.0
ansicolors==1.1.8
anyio==4.3.0
appengine-python-standard==1.1.6
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
astroid==3.2.2
asttokens==2.4.1
async-timeout==4.0.3
attrs==23.2.0
autopep8==2.0.4
Babel==2.15.0
bcrypt==4.1.3
beautifulsoup4==4.12.3
black==24.4.2
bleach==6.1.0
blessed==1.20.0
bokeh==3.4.1
boto3==1.34.111
botocore==1.34.111
cachetools==5.3.3
certifi==2024.2.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
codeflare-sdk==0.16.1
codeflare-torchx==0.6.0.dev2
colorama==0.4.6
colorful==0.5.6
comm==0.2.2
commonmark==0.9.1
contourpy==1.2.1
cryptography==40.0.2
cycler==0.12.1
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.14
deprecation==2.1.0
dill==0.3.8
distlib==0.3.8
dnspython==2.6.1
docker==7.1.0
docstring-to-markdown==0.15
docstring_parser==0.16
entrypoints==0.4
exceptiongroup==1.2.1
executing==1.2.0
fastjsonschema==2.19.1
filelock==3.14.0
fire==0.6.0
flake8==7.0.0
fonttools==4.51.0
fqdn==1.5.1
frozendict==2.4.4
frozenlist==1.4.1
fsspec==2024.5.0
gitdb==4.0.11
GitPython==3.1.43
google-api-core==2.19.0
google-auth==2.29.0
google-cloud-core==2.4.1
google-cloud-storage==2.16.0
google-crc32c==1.5.0
google-resumable-media==2.7.0
googleapis-common-protos==1.63.0
gpustat==1.1.1
grpcio==1.64.0
huggingface-hub==0.24.7
idna==3.7
importlib_metadata==7.1.0
importlib_resources==6.4.0
ipykernel==6.29.4
ipython==8.18.1
ipython-genutils==0.2.0
ipywidgets==8.1.2
isoduration==20.11.0
isort==5.13.2
jedi==0.19.1
Jinja2==3.1.4
jmespath==1.0.1
joblib==1.4.2
json5==0.9.25
jsonpointer==2.4
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter-bokeh==3.0.7
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter-resource-usage==0.7.2
jupyter-server-mathjax==0.2.6
jupyter-ydoc==0.2.5
jupyter_client==7.4.9
jupyter_core==5.7.2
jupyter_packaging==0.12.3
jupyter_server==2.13.0
jupyter_server_fileid==0.9.2
jupyter_server_proxy==4.0.0
jupyter_server_terminals==0.5.3
jupyter_server_ydoc==0.8.0
jupyterlab==3.6.7
jupyterlab-lsp==4.2.0
jupyterlab_git==0.44.0
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.10
kafka-python==2.0.2
kfp==2.7.0
kfp-kubernetes==1.2.0
kfp-pipeline-spec==0.3.0
kfp-server-api==2.0.5
kiwisolver==1.4.5
kubernetes==26.1.0
Markdown==3.6
MarkupSafe==2.1.5
matplotlib==3.8.4
matplotlib-inline==0.1.7
mccabe==0.7.0
micropipenv==1.6.0
minio==7.2.7
mistral_common==1.4.0
mistune==3.0.2
mock==5.1.0
mpmath==1.3.0
msgpack==1.0.8
multidict==6.0.5
mypy-extensions==1.0.0
mysql-connector-python==8.3.0
nbclassic==1.0.0
nbclient==0.10.0
nbconvert==7.16.4
nbdime==3.2.1
nbformat==5.10.4
nbgitpuller==1.2.1
nest-asyncio==1.6.0
networkx==3.2.1
notebook==6.5.7
notebook_shim==0.2.4
numpy==1.26.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-ml-py==12.550.52
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.5.40
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
odh-elyra==3.16.6
onnx==1.16.0
onnxconverter-common==1.13.0
opencensus==0.11.4
opencensus-context==0.1.3
openshift-client==1.0.18
overrides==7.7.0
packaging==24.0
pandas==2.2.2
pandocfilters==1.5.1
papermill==2.6.0
paramiko==3.4.0
parso==0.8.4
pathspec==0.12.1
pexpect==4.9.0
pillow==10.3.0
platformdirs==3.11.0
plotly==5.20.0
pluggy==1.5.0
prometheus_client==0.20.0
prompt-toolkit==3.0.43
proto-plus==1.23.0
protobuf==4.25.3
psutil==5.9.8
psycopg==3.1.19
ptyprocess==0.7.0
pure-eval==0.2.2
py-spy==0.3.14
pyarrow==16.1.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycodestyle==2.11.1
pycparser==2.22
pycryptodome==3.20.0
pydantic==2.9.1
pydantic_core==2.23.3
pydocstyle==6.3.0
pyflakes==3.2.0
PyGithub==2.3.0
Pygments==2.18.0
PyJWT==2.8.0
pylint==3.2.2
pymongo==4.6.3
PyNaCl==1.5.0
pyodbc==5.1.0
pyparsing==3.1.2
pyre-extensions==0.0.30
python-dateutil==2.9.0.post0
python-json-logger==2.0.7
python-lsp-jsonrpc==1.1.2
python-lsp-server==1.11.0
pytoolconfig==1.3.1
pytz==2024.1
PyYAML==6.0.1
pyzmq==26.0.3
ray==2.7.0
referencing==0.35.1
regex==2024.9.11
requests==2.32.2
requests-oauthlib==2.0.0
requests-toolbelt==0.10.1
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==12.6.0
rope==1.13.0
rpds-py==0.18.1
rsa==4.9
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.8
s3transfer==0.10.1
safetensors==0.4.5
scikit-learn==1.4.2
scipy==1.12.0
Send2Trash==1.8.3
sentencepiece==0.2.0
simpervisor==1.0.0
simple-parsing==0.1.6
six==1.16.0
skl2onnx==1.16.0
smart-open==7.0.4
smmap==5.0.1
sniffio==1.3.1
snowballstemmer==2.2.0
soupsieve==2.5
stack-data==0.6.3
sympy==1.12
tabulate==0.9.0
tenacity==8.3.0
tensorboard==2.16.2
tensorboard-data-server==0.7.2
termcolor==2.3.0
terminado==0.18.1
threadpoolctl==3.5.0
tiktoken==0.7.0
tinycss2==1.3.0
toml==0.10.2
tomli==2.0.1
tomlkit==0.12.5
torch==2.2.0
torchvision==0.17.2+cu121
tornado==6.4
tqdm==4.66.4
traitlets==5.14.3
triton==2.2.0
types-python-dateutil==2.9.0.20240316
typing-inspect==0.9.0
typing_extensions==4.11.0
tzdata==2024.1
ujson==5.10.0
uri-template==1.3.0
urllib3==1.26.18
virtualenv==20.21.0
watchdog==4.0.1
wcwidth==0.2.13
webcolors==1.13
webencodings==0.5.1
websocket-client==1.8.0
Werkzeug==3.0.3
whatthepatch==1.0.5
widgetsnbextension==4.0.10
wrapt==1.16.0
xformers==0.0.24
xyzservices==2024.4.0
y-py==0.6.2
yapf==0.40.2
yarl==1.9.4
yaspin==3.0.2
ypy-websocket==0.8.4
zipp==3.18.2
```

### Reproduction Steps

1. Follow the mistral_finetune_7b.ipynb nodebook
2. Reformated the dataset successfully using "!python -m utils.reformat_data  /path/to/dataset.jsonl"
3. Validated the dataset successfully using "!python -m utils.validate_data --train_yaml example.yaml"
4. Start training the model using "!torchrun --nproc-per-node 1 -m train example.yaml"

### Expected Behavior

Should be able to finish the training successfully as per the tutorial

### Additional Context

But ended up getting the following error:

> Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/app-root/src/mistral-finetune-original/train.py", line 328, in <module>
    fire.Fire(train)
  File "/opt/app-root/lib64/python3.9/site-packages/fire/core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/opt/app-root/lib64/python3.9/site-packages/fire/core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/opt/app-root/lib64/python3.9/site-packages/fire/core.py", line 693, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/opt/app-root/src/mistral-finetune-original/train.py", line 65, in train
    _train(args, exit_stack)
  File "/opt/app-root/src/mistral-finetune-original/train.py", line 171, in _train
    eval_batches = list(eval_data_loader)
  File "/opt/app-root/src/mistral-finetune-original/finetune/data/data_loader.py", line 137, in build_data_loader
    batch: Batch = batch_list.create_batch()
  File "/opt/app-root/src/mistral-finetune-original/finetune/data/data_loader.py", line 93, in create_batch
    x_np: np.ndarray = self.flatten_to_numpy(self.x, dtype=np.int64)
  File "/opt/app-root/src/mistral-finetune-original/finetune/data/data_loader.py", line 77, in flatten_to_numpy
    return np.array([el for sublist in list_of_lists for el in sublist], dtype=dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (32768,) + inhomogeneous part.
[2024-09-12 15:36:30,523] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 973) of binary: /opt/app-root/bin/python3.9
Traceback (most recent call last):
  File "/opt/app-root/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/app-root/lib64/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/opt/app-root/lib64/python3.9/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/opt/app-root/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/app-root/lib64/python3.9/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-12_15:36:30
  host      : train-the-model-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 973)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by ztkg257** [comment]
I have got same issue in python 3.10.9 

pip list 
absl-py                   2.1.0
annotated-types           0.7.0
anyio                     4.4.0
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.3.0
asttokens                 2.0.5
astunparse                1.6.3
async-lru                 2.0.4
attrs                     22.2.0
babel                     2.16.0
backcall                  0.2.0
bash_kernel               0.9.3
beautifulsoup4            4.11.1
bleach                    6.1.0
brotlipy                  0.7.0
certifi                   2022.12.7
cffi                      1.15.1
chardet                   4.0.0
charset-normalizer        2.0.4
comm                      0.2.2
conda                     23.1.0
conda-build               3.23.3
conda-content-trust       0.1.3
conda-package-handling    2.0.2
conda_package_streaming   0.7.0
cryptography              39.0.1
debugpy                   1.8.5
decorator                 5.1.1
defusedxml                0.7.1
dnspython                 2.3.0
docstring_parser          0.16
exceptiongroup            1.1.1
executing                 0.8.3
expecttest                0.1.4
fastjsonschema            2.20.0
filelock                  3.9.0
fire                      0.6.0
flit_core                 3.6.0
fqdn                      1.5.1
fsspec                    2024.9.0
glob2                     0.7
gmpy2                     2.1.2
grpcio                    1.66.1
h11                       0.14.0
httpcore                  1.0.5
httpx                     0.27.2
hypothesis                6.70.0
idna                      3.4
iniconfig                 2.0.0
ipykernel                 6.29.5
ipython                   8.10.0
ipywidgets                8.1.5
isoduration               20.11.0
jedi                      0.18.1
Jinja2                    3.1.2
json5                     0.9.25
jsonpointer               3.0.0
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
jupyter                   1.1.1
jupyter-archive           3.4.0
jupyter_client            8.6.2
jupyter-console           6.6.3
jupyter_core              5.7.2
jupyter-events            0.10.0
jupyter-http-over-ws      0.0.8
jupyter-lsp               2.2.5
jupyter_server            2.14.2
jupyter_server_terminals  0.5.3
jupyterlab                4.2.5
jupyterlab_pygments       0.3.0
jupyterlab_server         2.27.3
jupyterlab_widgets        3.0.13
libarchive-c              2.9
Markdown                  3.7
MarkupSafe                2.1.1
matplotlib-inline         0.1.6
mistral_common            1.4.0
mistune                   3.0.2
mkl-fft                   1.3.1
mkl-random                1.2.2
mkl-service               2.4.0
mpmath                    1.3.0
nbclient                  0.10.0
nbconvert                 7.16.4
nbformat                  5.10.4
nbzip                     0.1.0
nest-asyncio              1.6.0
networkx                  3.0
notebook                  7.2.2
notebook_shim             0.2.4
numpy                     1.23.5
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.19.3
nvidia-nvjitlink-cu12     12.6.68
nvidia-nvtx-cu12          12.1.105
overrides                 7.7.0
packaging                 24.1
pandocfilters             1.5.1
parso                     0.8.3
pexpect                   4.8.0
pickleshare               0.7.5
pillow                    10.4.0
pip                       22.3.1
pkginfo                   1.8.3
platformdirs              4.3.2
pluggy                    1.5.0
prometheus_client         0.20.0
prompt-toolkit            3.0.36
protobuf                  5.28.1
psutil                    5.9.0
ptyprocess                0.7.0
pure-eval                 0.2.2
pycosat                   0.6.4
pycparser                 2.21
pydantic                  2.9.1
pydantic_core             2.23.3
Pygments                  2.11.2
pyOpenSSL                 23.0.0
PySocks                   1.7.1
pytest                    8.3.3
python-dateutil           2.9.0.post0
python-etcd               0.4.5
python-json-logger        2.0.7
pytz                      2022.7
PyYAML                    6.0
pyzmq                     26.2.0
referencing               0.35.1
regex                     2024.9.11
requests                  2.32.3
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.20.0
ruamel.yaml               0.17.21
ruamel.yaml.clib          0.2.6
safetensors               0.4.5
Send2Trash                1.8.3
sentencepiece             0.2.0
setuptools                65.6.3
simple-parsing            0.1.6
six                       1.16.0
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.3.2.post1
stack-data                0.2.0
sympy                     1.11.1
tensorboard               2.17.1
tensorboard-data-server   0.7.2
termcolor                 2.4.0
terminado                 0.18.1
tiktoken                  0.7.0
tinycss2                  1.3.0
toml                      0.10.2
tomli                     2.0.1
toolz                     0.12.0
torch                     2.2.0
torchaudio                2.0.0
torchdata                 0.6.0
torchelastic              0.2.2
torchtext                 0.15.0
torchvision               0.15.0
tornado                   6.4.1
tqdm                      4.64.1
traitlets                 5.7.1
triton                    2.2.0
types-dataclasses         0.6.6
types-python-dateutil     2.9.0.20240906
typing_extensions         4.12.2
uri-template              1.3.0
urllib3                   1.26.14
wcwidth                   0.2.5
webcolors                 24.8.0
webencodings              0.5.1
websocket-client          1.8.0
Werkzeug                  3.0.4
wheel                     0.37.1
widgetsnbextension        4.0.13
xformers                  0.0.24
zstandard                 0.19.0

**Comment by nvnk3** [comment]
Thank you so much, this commit has the fix:
https://github.com/mistralai/mistral-finetune/commit/656df1c94c80ca9703ebc471c9f106c9b7a0bfa7
